import 'dart:convert';
import 'dart:io';

/// Run from mobile/: dart run tool/generate_translations.dart [--check]
void main(List<String> args) {
  const codes = ['ko', 'en', 'ja', 'zh_Hans', 'zh_Hant'];
  final catalogs = <String, Map<String, dynamic>>{};
  final placeholders = RegExp(r'\{\d+\}');
  for (final code in codes) {
    final values = jsonDecode(
      File('lib/l10n/catalogs/$code.json').readAsStringSync(),
    ) as Map<String, dynamic>;
    catalogs[code] = values;
    final source = catalogs['ko']!;
    if (values.length != source.length ||
        !values.keys.toSet().containsAll(source.keys)) {
      throw FormatException('Translation keys differ: $code');
    }
    for (final key in values.keys) {
      final value = values[key];
      if (value is! String || value.isEmpty) {
        throw FormatException('Empty translation: $code $key');
      }
      final expected = placeholders.allMatches(key).map((m) => m[0]).toSet();
      final actual = placeholders.allMatches(value).map((m) => m[0]).toSet();
      if (expected.length != actual.length || !actual.containsAll(expected)) {
        throw FormatException('Placeholder mismatch: $code $key');
      }
    }
  }
  String literal(String value) => jsonEncode(value).replaceAll(r'$', r'\$');
  final out =
      StringBuffer(
          '// Generated by tool/generate_translations.dart. Edit catalogs/*.json.\n',
        )
        ..writeln('// dart format off')
        ..writeln('const translationCatalogs = <String, Map<String, String>>{');
  for (final code in codes) {
    out.writeln('  ${literal(code)}: {');
    final keys = catalogs[code]!.keys.toList()..sort();
    for (final key in keys) {
      out.writeln(
        '    ${literal(key)}: ${literal(catalogs[code]![key] as String)},',
      );
    }
    out.writeln('  },');
  }
  out.writeln('};');
  final file = File('lib/l10n/catalogs.g.dart');
  if (args.contains('--check')) {
    if (!file.existsSync() || file.readAsStringSync() != out.toString()) {
      throw StateError('Run dart run tool/generate_translations.dart');
    }
  } else {
    file.writeAsStringSync(out.toString());
  }
  stdout.writeln(
    'Validated ${catalogs['ko']!.length} messages across ${codes.length} locales.',
  );
}
